### ISSUE TITLE
Allow option for two way data bind for selected

### ISSUE THREAD

**Issue by nadeemkhedr** [brunokrebs/bng-selector#1]
I know the way to go is two way data binding, and it's never recommended to do two-way data binding, but the problem with angular there is no fast way to pass an action that change parent's value, in ember for example, there is a built in action that will mutate the value

The problem comes when using the component with long forms, its cumbersome to create a callback for each component 

What you could do is check if there is a on select action passed then call it, else mutate the value 

I could do a PR if you are interested

**Comment by brunokrebs** [comment]
Sure, go ahead @nadeemkhedr.

**Comment by brunokrebs** [comment]
But I was reading your issue again and I'm thinking, why would you need to create a callback for each component?

Take a look at the [following fiddle that I've created](https://jsfiddle.net/brunokrebs/es0hg9vv/10/). It shows how to use just one callback to multiple items.

**Comment by brunokrebs** [comment]
By the way, take a look [at the angular 1.5 component docs](https://docs.angularjs.org/guide/component). It states that components should not update domain, they should communicate through callbacks.

"Instead of manipulating Input Data, the component calls the correct Output Event with the changed data."
